In [3]:
#importing pandas

import numpy as np
import pandas as pd

In [4]:
#load the dataset

df = pd.read_csv('healthcare-dataset-stroke-data.csv')

In [5]:
#view the dataset
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.00,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.00,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.00,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.00,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.00,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
5,56669,Male,81.00,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1
6,53882,Male,74.00,1,1,Yes,Private,Rural,70.09,27.4,never smoked,1
7,10434,Female,69.00,0,0,No,Private,Urban,94.39,22.8,never smoked,1
8,27419,Female,59.00,0,0,Yes,Private,Rural,76.15,NaN,Unknown,1
9,60491,Female,78.00,0,0,Yes,Private,Urban,58.57,24.2,Unknown,1
10,12109,Female,81.00,1,0,Yes,Private,Rural,80.43,29.7,never smoked,1
11,12095,Female,61.00,0,1,Yes,Govt_job,Rural,120.46,36.8,smokes,1
12,12175,Female,54.00,0,0,Yes,Private,Urban,104.51,27.3,smokes,1
13,8213,Male,78.00,0,1,Yes,Private,Urban,219.84,NaN,Unknown,1
14,5317,Female,79.00,0,1,Yes,Private,Urban,214.09,28.2,never smoked,1
15,58202,Female,50.00,1,0,Yes,Self-employed,Rural,167.41,30.9,never smoked,1
16,56112,Male,64.00,0,1,Yes,Private,Urban,191.61,37.5,smokes,1
17,34120,Male,75.00,1,0,Yes,Private,Urban,221.29,25.8,smokes,1
18,27458,Female,60.00,0,0,No,Private,Urban,89.22,37.8,never smoked,1
19,25226,Male,57.00,0,1,No,Govt_job,Urban,217.08,NaN,Unknown,1
20,70630,Female,71.00,0,0,Yes,Govt_job,Rural,193.94,22.4,smokes,1
21,13861,Female,52.00,1,0,Yes,Self-employed,Urban,233.29,48.9,never smoked,1
22,68794,Female,79.00,0,0,Yes,Self-employed,Urban,228.70,26.6,never smoked,1
23,64778,Male,82.00,0,1,Yes,Private,Rural,208.30,32.5,Unknown,1
24,4219,Male,71.00,0,0,Yes,Private,Urban,102.87,27.2,formerly smoked,1
25,70822,Male,80.00,0,0,Yes,Self-employed,Rural,104.12,23.5,never smoked,1
26,38047,Female,65.00,0,0,Yes,Private,Rural,100.98,28.2,formerly smoked,1
27,61843,Male,58.00,0,0,Yes,Private,Rural,189.84,NaN,Unknown,1
28,54827,Male,69.00,0,1,Yes,Self-employed,Urban,195.23,28.3,smokes,1
29,69160,Male,59.00,0,0,Yes,Private,Rural,211.78,NaN,formerly smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5080,22691,Female,29.00,0,0,Yes,Self-employed,Urban,90.52,28.0,never smoked,0
5081,37680,Male,55.00,0,0,Yes,Govt_job,Rural,108.35,40.8,formerly smoked,0
5082,24552,Female,44.00,0,0,Yes,Private,Rural,72.03,37.5,smokes,0
5083,72914,Female,19.00,0,0,No,Private,Urban,90.57,24.2,Unknown,0
5084,29540,Male,67.00,0,0,Yes,Private,Rural,97.04,26.9,smokes,0
5085,53525,Female,72.00,0,0,Yes,Private,Urban,83.89,33.1,formerly smoked,0
5086,65411,Female,51.00,0,0,Yes,Private,Urban,152.56,21.8,Unknown,0
5087,26214,Female,63.00,0,0,Yes,Self-employed,Rural,75.93,34.7,formerly smoked,0
5088,22190,Female,64.00,1,0,Yes,Self-employed,Urban,76.89,30.2,Unknown,0
5089,56714,Female,0.72,0,0,No,children,Rural,62.13,16.8,Unknown,0
5090,4211,Male,26.00,0,0,No,Govt_job,Rural,100.85,21.0,smokes,0
5091,6369,Male,59.00,1,0,Yes,Private,Rural,95.05,30.9,never smoked,0
5092,56799,Male,76.00,0,0,Yes,Govt_job,Urban,82.35,38.9,never smoked,0
5093,32235,Female,45.00,1,0,Yes,Govt_job,Rural,95.02,NaN,smokes,0
5094,28048,Male,13.00,0,0,No,children,Urban,82.38,24.3,Unknown,0
5095,68598,Male,1.08,0,0,No,children,Rural,79.15,17.4,Unknown,0
5096,41512,Male,57.00,0,0,Yes,Govt_job,Rural,76.62,28.2,never smoked,0
5097,64520,Male,68.00,0,0,Yes,Self-employed,Urban,91.68,40.8,Unknown,0
5098,579,Male,9.00,0,0,No,children,Urban,71.88,17.5,Unknown,0
5099,7293,Male,40.00,0,0,Yes,Private,Rural,83.94,NaN,smokes,0
5100,68398,Male,82.00,1,0,Yes,Self-employed,Rural,71.97,28.3,never smoked,0
5101,36901,Female,45.00,0,0,Yes,Private,Urban,97.95,24.5,Unknown,0
5102,45010,Female,57.00,0,0,Yes,Private,Rural,77.93,21.7,never smoked,0
5103,22127,Female,18.00,0,0,No,Private,Urban,82.85,46.9,Unknown,0
5104,14180,Female,13.00,0,0,No,children,Rural,103.08,18.6,Unknown,0
5105,18234,Female,80.00,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.00,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.00,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.00,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.00,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [6]:
#PRE-PROCESSING
df.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

In [9]:
#change categorical-data to numerical-data

from sklearn.preprocessing import LabelEncoder
category_data = ['gender', 'ever_married','work_type','Residence_type','smoking_status']

for data in category_data:
  df[data] = LabelEncoder().fit_transform(df[data])

df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,1,67.00,0,1,1,2,1,228.69,36.6,1,1
1,51676,0,61.00,0,0,1,3,0,202.21,NaN,2,1
2,31112,1,80.00,0,1,1,2,0,105.92,32.5,2,1
3,60182,0,49.00,0,0,1,2,1,171.23,34.4,3,1
4,1665,0,79.00,1,0,1,3,0,174.12,24.0,2,1
5,56669,1,81.00,0,0,1,2,1,186.21,29.0,1,1
6,53882,1,74.00,1,1,1,2,0,70.09,27.4,2,1
7,10434,0,69.00,0,0,0,2,1,94.39,22.8,2,1
8,27419,0,59.00,0,0,1,2,0,76.15,NaN,0,1
9,60491,0,78.00,0,0,1,2,1,58.57,24.2,0,1
10,12109,0,81.00,1,0,1,2,0,80.43,29.7,2,1
11,12095,0,61.00,0,1,1,0,0,120.46,36.8,3,1
12,12175,0,54.00,0,0,1,2,1,104.51,27.3,3,1
13,8213,1,78.00,0,1,1,2,1,219.84,NaN,0,1
14,5317,0,79.00,0,1,1,2,1,214.09,28.2,2,1
15,58202,0,50.00,1,0,1,3,0,167.41,30.9,2,1
16,56112,1,64.00,0,1,1,2,1,191.61,37.5,3,1
17,34120,1,75.00,1,0,1,2,1,221.29,25.8,3,1
18,27458,0,60.00,0,0,0,2,1,89.22,37.8,2,1
19,25226,1,57.00,0,1,0,0,1,217.08,NaN,0,1
20,70630,0,71.00,0,0,1,0,0,193.94,22.4,3,1
21,13861,0,52.00,1,0,1,3,1,233.29,48.9,2,1
22,68794,0,79.00,0,0,1,3,1,228.70,26.6,2,1
23,64778,1,82.00,0,1,1,2,0,208.30,32.5,0,1
24,4219,1,71.00,0,0,1,2,1,102.87,27.2,1,1
25,70822,1,80.00,0,0,1,3,0,104.12,23.5,2,1
26,38047,0,65.00,0,0,1,2,0,100.98,28.2,1,1
27,61843,1,58.00,0,0,1,2,0,189.84,NaN,0,1
28,54827,1,69.00,0,1,1,3,1,195.23,28.3,3,1
29,69160,1,59.00,0,0,1,2,0,211.78,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5080,22691,0,29.00,0,0,1,3,1,90.52,28.0,2,0
5081,37680,1,55.00,0,0,1,0,0,108.35,40.8,1,0
5082,24552,0,44.00,0,0,1,2,0,72.03,37.5,3,0
5083,72914,0,19.00,0,0,0,2,1,90.57,24.2,0,0
5084,29540,1,67.00,0,0,1,2,0,97.04,26.9,3,0
5085,53525,0,72.00,0,0,1,2,1,83.89,33.1,1,0
5086,65411,0,51.00,0,0,1,2,1,152.56,21.8,0,0
5087,26214,0,63.00,0,0,1,3,0,75.93,34.7,1,0
5088,22190,0,64.00,1,0,1,3,1,76.89,30.2,0,0
5089,56714,0,0.72,0,0,0,4,0,62.13,16.8,0,0
5090,4211,1,26.00,0,0,0,0,0,100.85,21.0,3,0
5091,6369,1,59.00,1,0,1,2,0,95.05,30.9,2,0
5092,56799,1,76.00,0,0,1,0,1,82.35,38.9,2,0
5093,32235,0,45.00,1,0,1,0,0,95.02,NaN,3,0
5094,28048,1,13.00,0,0,0,4,1,82.38,24.3,0,0
5095,68598,1,1.08,0,0,0,4,0,79.15,17.4,0,0
5096,41512,1,57.00,0,0,1,0,0,76.62,28.2,2,0
5097,64520,1,68.00,0,0,1,3,1,91.68,40.8,0,0
5098,579,1,9.00,0,0,0,4,1,71.88,17.5,0,0
5099,7293,1,40.00,0,0,1,2,0,83.94,NaN,3,0
5100,68398,1,82.00,1,0,1,3,0,71.97,28.3,2,0
5101,36901,0,45.00,0,0,1,2,1,97.95,24.5,0,0
5102,45010,0,57.00,0,0,1,2,0,77.93,21.7,2,0
5103,22127,0,18.00,0,0,0,2,1,82.85,46.9,0,0
5104,14180,0,13.00,0,0,0,4,0,103.08,18.6,0,0
5105,18234,0,80.00,1,0,1,2,1,83.75,NaN,2,0
5106,44873,0,81.00,0,0,1,3,1,125.20,40.0,2,0
5107,19723,0,35.00,0,0,1,3,0,82.99,30.6,2,0
5108,37544,1,51.00,0,0,1,2,0,166.29,25.6,1,0
5109,44679,0,44.00,0,0,1,0,1,85.28,26.2,0,0

In [8]:
#Category Data Changed to Numerical Data are as Follows
 
""" Smoking Status -> formerly smoked = 1, never smoked = 2, smokes = 3, unknown = 0
    Residence -> Urban = 1, Rural = 0
    Gender -> Male = 1, Female = 0, Other = 2
    Work Type -> Private = 2, Self-Employed = 3, Govtjob = 0, children = 1, never_worked = 4
    marriage status -> Married = 1, Single = 0
 """

' Smoking Status -> formerly smoked = 1, never smoked = 2, smokes = 3, unknown = 0\n    Residence -> Urban = 1, Rural = 0\n    Gender -> Male = 1, Female = 0, Other = 2\n    Work Type -> Private = 2, Self-Employed = 3, Govtjob = 0, children = 1, never_worked = 4\n    marriage status -> Married = 1, Single = 0\n '

In [10]:
#Check For Null Values
df.isnull()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,True,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,True,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,True,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,True,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
5080,False,False,False,False,False,False,False,False,False,False,False,False
5081,False,False,False,False,False,False,False,False,False,False,False,False
5082,False,False,False,False,False,False,False,False,False,False,False,False
5083,False,False,False,False,False,False,False,False,False,False,False,False
5084,False,False,False,False,False,False,False,False,False,False,False,False
5085,False,False,False,False,False,False,False,False,False,False,False,False
5086,False,False,False,False,False,False,False,False,False,False,False,False
5087,False,False,False,False,False,False,False,False,False,False,False,False
5088,False,False,False,False,False,False,False,False,False,False,False,False
5089,False,False,False,False,False,False,False,False,False,False,False,False
5090,False,False,False,False,False,False,False,False,False,False,False,False
5091,False,False,False,False,False,False,False,False,False,False,False,False
5092,False,False,False,False,False,False,False,False,False,False,False,False
5093,False,False,False,False,False,False,False,False,False,True,False,False
5094,False,False,False,False,False,False,False,False,False,False,False,False
5095,False,False,False,False,False,False,False,False,False,False,False,False
5096,False,False,False,False,False,False,False,False,False,False,False,False
5097,False,False,False,False,False,False,False,False,False,False,False,False
5098,False,False,False,False,False,False,False,False,False,False,False,False
5099,False,False,False,False,False,False,False,False,False,True,False,False
5100,False,False,False,False,False,False,False,False,False,False,False,False
5101,False,False,False,False,False,False,False,False,False,False,False,False
5102,False,False,False,False,False,False,False,False,False,False,False,False
5103,False,False,False,False,False,False,False,False,False,False,False,False
5104,False,False,False,False,False,False,False,False,False,False,False,False
5105,False,False,False,False,False,False,False,False,False,True,False,False
5106,False,False,False,False,False,False,False,False,False,False,False,False
5107,False,False,False,False,False,False,False,False,False,False,False,False
5108,False,False,False,False,False,False,False,False,False,False,False,False
5109,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
#bmi has null values
df['bmi'].isnull()

0       False
1        True
2       False
3       False
4       False
5       False
6       False
7       False
8        True
9       False
10      False
11      False
12      False
13       True
14      False
15      False
16      False
17      False
18      False
19       True
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27       True
28      False
29       True
        ...
5080    False
5081    False
5082    False
5083    False
5084    False
5085    False
5086    False
5087    False
5088    False
5089    False
5090    False
5091    False
5092    False
5093     True
5094    False
5095    False
5096    False
5097    False
5098    False
5099     True
5100    False
5101    False
5102    False
5103    False
5104    False
5105     True
5106    False
5107    False
5108    False
5109    False
Name: bmi, Length: 5110, dtype: bool

In [12]:
#replace these null values with mean value ( avg ) of the column

#mean-value of bmi
mean = np.mean(df['bmi'])    
mean  

#use fillna to replace null-values

df['bmi'].fillna(mean,inplace=True)
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,1,67.00,0,1,1,2,1,228.69,36.600000,1,1
1,51676,0,61.00,0,0,1,3,0,202.21,28.893237,2,1
2,31112,1,80.00,0,1,1,2,0,105.92,32.500000,2,1
3,60182,0,49.00,0,0,1,2,1,171.23,34.400000,3,1
4,1665,0,79.00,1,0,1,3,0,174.12,24.000000,2,1
5,56669,1,81.00,0,0,1,2,1,186.21,29.000000,1,1
6,53882,1,74.00,1,1,1,2,0,70.09,27.400000,2,1
7,10434,0,69.00,0,0,0,2,1,94.39,22.800000,2,1
8,27419,0,59.00,0,0,1,2,0,76.15,28.893237,0,1
9,60491,0,78.00,0,0,1,2,1,58.57,24.200000,0,1
10,12109,0,81.00,1,0,1,2,0,80.43,29.700000,2,1
11,12095,0,61.00,0,1,1,0,0,120.46,36.800000,3,1
12,12175,0,54.00,0,0,1,2,1,104.51,27.300000,3,1
13,8213,1,78.00,0,1,1,2,1,219.84,28.893237,0,1
14,5317,0,79.00,0,1,1,2,1,214.09,28.200000,2,1
15,58202,0,50.00,1,0,1,3,0,167.41,30.900000,2,1
16,56112,1,64.00,0,1,1,2,1,191.61,37.500000,3,1
17,34120,1,75.00,1,0,1,2,1,221.29,25.800000,3,1
18,27458,0,60.00,0,0,0,2,1,89.22,37.800000,2,1
19,25226,1,57.00,0,1,0,0,1,217.08,28.893237,0,1
20,70630,0,71.00,0,0,1,0,0,193.94,22.400000,3,1
21,13861,0,52.00,1,0,1,3,1,233.29,48.900000,2,1
22,68794,0,79.00,0,0,1,3,1,228.70,26.600000,2,1
23,64778,1,82.00,0,1,1,2,0,208.30,32.500000,0,1
24,4219,1,71.00,0,0,1,2,1,102.87,27.200000,1,1
25,70822,1,80.00,0,0,1,3,0,104.12,23.500000,2,1
26,38047,0,65.00,0,0,1,2,0,100.98,28.200000,1,1
27,61843,1,58.00,0,0,1,2,0,189.84,28.893237,0,1
28,54827,1,69.00,0,1,1,3,1,195.23,28.300000,3,1
29,69160,1,59.00,0,0,1,2,0,211.78,28.893237,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5080,22691,0,29.00,0,0,1,3,1,90.52,28.000000,2,0
5081,37680,1,55.00,0,0,1,0,0,108.35,40.800000,1,0
5082,24552,0,44.00,0,0,1,2,0,72.03,37.500000,3,0
5083,72914,0,19.00,0,0,0,2,1,90.57,24.200000,0,0
5084,29540,1,67.00,0,0,1,2,0,97.04,26.900000,3,0
5085,53525,0,72.00,0,0,1,2,1,83.89,33.100000,1,0
5086,65411,0,51.00,0,0,1,2,1,152.56,21.800000,0,0
5087,26214,0,63.00,0,0,1,3,0,75.93,34.700000,1,0
5088,22190,0,64.00,1,0,1,3,1,76.89,30.200000,0,0
5089,56714,0,0.72,0,0,0,4,0,62.13,16.800000,0,0
5090,4211,1,26.00,0,0,0,0,0,100.85,21.000000,3,0
5091,6369,1,59.00,1,0,1,2,0,95.05,30.900000,2,0
5092,56799,1,76.00,0,0,1,0,1,82.35,38.900000,2,0
5093,32235,0,45.00,1,0,1,0,0,95.02,28.893237,3,0
5094,28048,1,13.00,0,0,0,4,1,82.38,24.300000,0,0
5095,68598,1,1.08,0,0,0,4,0,79.15,17.400000,0,0
5096,41512,1,57.00,0,0,1,0,0,76.62,28.200000,2,0
5097,64520,1,68.00,0,0,1,3,1,91.68,40.800000,0,0
5098,579,1,9.00,0,0,0,4,1,71.88,17.500000,0,0
5099,7293,1,40.00,0,0,1,2,0,83.94,28.893237,3,0
5100,68398,1,82.00,1,0,1,3,0,71.97,28.300000,2,0
5101,36901,0,45.00,0,0,1,2,1,97.95,24.500000,0,0
5102,45010,0,57.00,0,0,1,2,0,77.93,21.700000,2,0
5103,22127,0,18.00,0,0,0,2,1,82.85,46.900000,0,0
5104,14180,0,13.00,0,0,0,4,0,103.08,18.600000,0,0
5105,18234,0,80.00,1,0,1,2,1,83.75,28.893237,2,0
5106,44873,0,81.00,0,0,1,3,1,125.20,40.000000,2,0
5107,19723,0,35.00,0,0,1,3,0,82.99,30.600000,2,0
5108,37544,1,51.00,0,0,1,2,0,166.29,25.600000,1,0
5109,44679,0,44.00,0,0,1,0,1,85.28,26.200000,0,0

In [24]:
df = df.drop(columns='id')

In [25]:
#Normalization = 0-1 Range

from sklearn.preprocessing import MinMaxScaler

#make age,bmi,glucose-levels in 0-1 range

df[['gender','age','work_type','avg_glucose_level','bmi','smoking_status']] = MinMaxScaler().fit_transform(df[['gender','age','work_type','avg_glucose_level','bmi','smoking_status']])

C:\Users\SREERAM S\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

In [26]:
df

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,0.5,0.816895,0,1,1,0.50,1,0.801265,0.301260,0.333333,1
1,0.0,0.743652,0,0,1,0.75,0,0.679023,0.212981,0.666667,1
2,0.5,0.975586,0,1,1,0.50,0,0.234512,0.254296,0.666667,1
3,0.0,0.597168,0,0,1,0.50,1,0.536008,0.276060,1.000000,1
4,0.0,0.963379,1,0,1,0.75,0,0.549349,0.156930,0.666667,1
5,0.5,0.987793,0,0,1,0.50,1,0.605161,0.214204,0.333333,1
6,0.5,0.902344,1,1,1,0.50,0,0.069107,0.195876,0.666667,1
7,0.0,0.841309,0,0,0,0.50,1,0.181285,0.143184,0.666667,1
8,0.0,0.719238,0,0,1,0.50,0,0.097082,0.212981,0.000000,1
9,0.0,0.951172,0,0,1,0.50,1,0.015927,0.159221,0.000000,1
10,0.0,0.987793,1,0,1,0.50,0,0.116841,0.222222,0.666667,1
11,0.0,0.743652,0,1,1,0.00,0,0.301634,0.303551,1.000000,1
12,0.0,0.658203,0,0,1,0.50,1,0.228003,0.194731,1.000000,1
13,0.5,0.951172,0,1,1,0.50,1,0.760410,0.212981,0.000000,1
14,0.0,0.963379,0,1,1,0.50,1,0.733866,0.205040,0.666667,1
15,0.0,0.609375,1,0,1,0.75,0,0.518373,0.235968,0.666667,1
16,0.5,0.780273,0,1,1,0.50,1,0.630090,0.311569,1.000000,1
17,0.5,0.914551,1,0,1,0.50,1,0.767104,0.177549,1.000000,1
18,0.0,0.731445,0,0,0,0.50,1,0.157419,0.315006,0.666667,1
19,0.5,0.694824,0,1,0,0.00,1,0.747669,0.212981,0.000000,1
20,0.0,0.865723,0,0,1,0.00,0,0.640846,0.138603,1.000000,1
21,0.0,0.633789,1,0,1,0.75,1,0.822500,0.442153,0.666667,1
22,0.0,0.963379,0,0,1,0.75,1,0.801311,0.186712,0.666667,1
23,0.5,1.000000,0,1,1,0.50,0,0.707137,0.254296,0.000000,1
24,0.5,0.865723,0,0,1,0.50,1,0.220432,0.193585,0.333333,1
25,0.5,0.975586,0,0,1,0.75,0,0.226203,0.151203,0.666667,1
26,0.0,0.792480,0,0,1,0.50,0,0.211707,0.205040,0.333333,1
27,0.5,0.707031,0,0,1,0.50,0,0.621919,0.212981,0.000000,1
28,0.5,0.841309,0,1,1,0.75,1,0.646801,0.206186,1.000000,1
29,0.5,0.719238,0,0,1,0.50,0,0.723202,0.212981,0.333333,1
...,...,...,...,...,...,...,...,...,...,...,...
5080,0.0,0.353027,0,0,1,0.75,1,0.163420,0.202749,0.666667,0
5081,0.5,0.670410,0,0,1,0.00,0,0.245730,0.349370,0.333333,0
5082,0.0,0.536133,0,0,1,0.50,0,0.078063,0.311569,1.000000,0
5083,0.0,0.230957,0,0,0,0.50,1,0.163651,0.159221,0.000000,0
5084,0.5,0.816895,0,0,1,0.50,0,0.193519,0.190149,1.000000,0
5085,0.0,0.877930,0,0,1,0.50,1,0.132813,0.261168,0.333333,0
5086,0.0,0.621582,0,0,1,0.50,1,0.449820,0.131730,0.000000,0
5087,0.0,0.768066,0,0,1,0.75,0,0.096067,0.279496,0.333333,0
5088,0.0,0.780273,1,0,1,0.75,1,0.100499,0.227950,0.000000,0
5089,0.0,0.007812,0,0,0,1.00,0,0.032361,0.074456,0.000000,0
5090,0.5,0.316406,0,0,0,0.00,0,0.211107,0.122566,1.000000,0
5091,0.5,0.719238,1,0,1,0.50,0,0.184332,0.235968,0.666667,0
5092,0.5,0.926758,0,0,1,0.00,1,0.125704,0.327606,0.666667,0
5093,0.0,0.548340,1,0,1,0.00,0,0.184194,0.212981,1.000000,0
5094,0.5,0.157715,0,0,0,1.00,1,0.125842,0.160367,0.000000,0
5095,0.5,0.012207,0,0,0,1.00,0,0.110932,0.081329,0.000000,0
5096,0.5,0.694824,0,0,1,0.00,0,0.099252,0.205040,0.666667,0
5097,0.5,0.829102,0,0,1,0.75,1,0.168775,0.349370,0.000000,0
5098,0.5,0.108887,0,0,0,1.00,1,0.077371,0.082474,0.000000,0
5099,0.5,0.487305,0,0,1,0.50,0,0.133044,0.212981,1.000000,0
5100,0.5,1.000000,1,0,1,0.75,0,0.077786,0.206186,0.666667,0
5101,0.0,0.548340,0,0,1,0.50,1,0.197720,0.162658,0.000000,0
5102,0.0,0.694824,0,0,1,0.50,0,0.105300,0.130584,0.666667,0
5103,0.0,0.218750,0,0,0,0.50,1,0.128012,0.419244,0.000000,0
5104,0.0,0.157715,0,0,0,1.00,0,0.221402,0.095074,0.000000,0
5105,0.0,0.975586,1,0,1,0.50,1,0.132167,0.212981,0.666667,0
5106,0.0,0.987793,0,0,1,0.75,1,0.323516,0.340206,0.666667,0
5107,0.0,0.426270,0,0,1,0.75,0,0.128658,0.232532,0.666667,0
5108,0.5,0.621582,0,0,1,0.50,0,0.513203,0.175258,0.333333,0
5109,0.0,0.536133,0,0,1,0.00,1,0.139230,0.182131,0.000000,0

In [27]:
#features-target set
x = df.drop(columns='stroke')
y = df['stroke']

In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [29]:
#split train-dataset - 80% and test-data - 20%

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)

In [30]:
#DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [31]:
#Predict-test-data set

y_predict = model.predict(x_test)
y_predict

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [32]:
#to check accuracy - compare test value and predicted value

accuracy = accuracy_score(y_test,y_predict)
accuracy

0.9129158512720157

In [33]:

pred = model.predict([[0.0, 0.975586,1,0,1,0.50,1,0.132167,0.212981,0.666667]])

print(pred)

[0]

In [66]:
print((67-0.08)/(82-0.08))

0.81689453125

In [34]:
#CREATE A NEW DATAFRAME FOR INPUT-REFERENCE

datas = pd.read_csv('healthcare-dataset-stroke-data.csv')
datas

#change categorical-data to numerical-data

from sklearn.preprocessing import LabelEncoder
category_data = ['gender', 'ever_married','work_type','Residence_type','smoking_status']

for data in category_data:
  datas[data] = LabelEncoder().fit_transform(df[data])


#use fillna to replace null-values
mean = np.mean(datas['bmi'])    
mean  

datas['bmi'].fillna(mean,inplace=True)

datas = datas.drop(columns='id')
datas

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1,67.00,0,1,1,2,1,228.69,36.600000,1,1
1,0,61.00,0,0,1,3,0,202.21,28.893237,2,1
2,1,80.00,0,1,1,2,0,105.92,32.500000,2,1
3,0,49.00,0,0,1,2,1,171.23,34.400000,3,1
4,0,79.00,1,0,1,3,0,174.12,24.000000,2,1
5,1,81.00,0,0,1,2,1,186.21,29.000000,1,1
6,1,74.00,1,1,1,2,0,70.09,27.400000,2,1
7,0,69.00,0,0,0,2,1,94.39,22.800000,2,1
8,0,59.00,0,0,1,2,0,76.15,28.893237,0,1
9,0,78.00,0,0,1,2,1,58.57,24.200000,0,1
10,0,81.00,1,0,1,2,0,80.43,29.700000,2,1
11,0,61.00,0,1,1,0,0,120.46,36.800000,3,1
12,0,54.00,0,0,1,2,1,104.51,27.300000,3,1
13,1,78.00,0,1,1,2,1,219.84,28.893237,0,1
14,0,79.00,0,1,1,2,1,214.09,28.200000,2,1
15,0,50.00,1,0,1,3,0,167.41,30.900000,2,1
16,1,64.00,0,1,1,2,1,191.61,37.500000,3,1
17,1,75.00,1,0,1,2,1,221.29,25.800000,3,1
18,0,60.00,0,0,0,2,1,89.22,37.800000,2,1
19,1,57.00,0,1,0,0,1,217.08,28.893237,0,1
20,0,71.00,0,0,1,0,0,193.94,22.400000,3,1
21,0,52.00,1,0,1,3,1,233.29,48.900000,2,1
22,0,79.00,0,0,1,3,1,228.70,26.600000,2,1
23,1,82.00,0,1,1,2,0,208.30,32.500000,0,1
24,1,71.00,0,0,1,2,1,102.87,27.200000,1,1
25,1,80.00,0,0,1,3,0,104.12,23.500000,2,1
26,0,65.00,0,0,1,2,0,100.98,28.200000,1,1
27,1,58.00,0,0,1,2,0,189.84,28.893237,0,1
28,1,69.00,0,1,1,3,1,195.23,28.300000,3,1
29,1,59.00,0,0,1,2,0,211.78,28.893237,1,1
...,...,...,...,...,...,...,...,...,...,...,...
5080,0,29.00,0,0,1,3,1,90.52,28.000000,2,0
5081,1,55.00,0,0,1,0,0,108.35,40.800000,1,0
5082,0,44.00,0,0,1,2,0,72.03,37.500000,3,0
5083,0,19.00,0,0,0,2,1,90.57,24.200000,0,0
5084,1,67.00,0,0,1,2,0,97.04,26.900000,3,0
5085,0,72.00,0,0,1,2,1,83.89,33.100000,1,0
5086,0,51.00,0,0,1,2,1,152.56,21.800000,0,0
5087,0,63.00,0,0,1,3,0,75.93,34.700000,1,0
5088,0,64.00,1,0,1,3,1,76.89,30.200000,0,0
5089,0,0.72,0,0,0,4,0,62.13,16.800000,0,0
5090,1,26.00,0,0,0,0,0,100.85,21.000000,3,0
5091,1,59.00,1,0,1,2,0,95.05,30.900000,2,0
5092,1,76.00,0,0,1,0,1,82.35,38.900000,2,0
5093,0,45.00,1,0,1,0,0,95.02,28.893237,3,0
5094,1,13.00,0,0,0,4,1,82.38,24.300000,0,0
5095,1,1.08,0,0,0,4,0,79.15,17.400000,0,0
5096,1,57.00,0,0,1,0,0,76.62,28.200000,2,0
5097,1,68.00,0,0,1,3,1,91.68,40.800000,0,0
5098,1,9.00,0,0,0,4,1,71.88,17.500000,0,0
5099,1,40.00,0,0,1,2,0,83.94,28.893237,3,0
5100,1,82.00,1,0,1,3,0,71.97,28.300000,2,0
5101,0,45.00,0,0,1,2,1,97.95,24.500000,0,0
5102,0,57.00,0,0,1,2,0,77.93,21.700000,2,0
5103,0,18.00,0,0,0,2,1,82.85,46.900000,0,0
5104,0,13.00,0,0,0,4,0,103.08,18.600000,0,0
5105,0,80.00,1,0,1,2,1,83.75,28.893237,2,0
5106,0,81.00,0,0,1,3,1,125.20,40.000000,2,0
5107,0,35.00,0,0,1,3,0,82.99,30.600000,2,0
5108,1,51.00,0,0,1,2,0,166.29,25.600000,1,0
5109,0,44.00,0,0,1,0,1,85.28,26.200000,0,0

In [47]:
max(datas['bmi'])

97.6

In [36]:
def prediction(g,a,hyt,ht,m,w,r,gl,b,s):

  #gender
  if g == "male":
    g = 1
  elif g == "female":
    g = 0
  else:
    g = 2

  #age
  a = ((a - min(datas['age']))/(max(datas['age']) - min(datas['age'])))

  #tension
  if hyt == "yes":
    hyt = 1
  elif hyt == "no":
    hyt = 0


  #heart-issues
  if ht == "yes":
    ht = 1
  elif ht == "no":
    ht = 0

  
  #married
  if m == "yes":
    m = 1
  elif m == "no":
    m = 0


  #work-type
  if w == "government":
    w = 0
  elif w == "student":
    w = 1
  elif w == "private":
    w = 2
  elif w == "self-employed":
    w = 3
  else:
    w = 4


  #residence-type
  if r == "urban":
    r = 1
  else:
    r = 0


  #glucose-levels
  if gl == "i do not know":
    gl = np.mean(datas['avg_glucose_level'])
  else:
    gl = ((int(gl) - min(datas['avg_glucose_level']))/(max(datas['avg_glucose_level']) - min(datas['avg_glucose_level'])))

  
  #bmi
  b = ((b - min(datas['bmi']))/(max(datas['bmi']) - min(datas['bmi'])))


  #smoking
  if s == "unknown":
    s = 0
  elif s == "never smoked":
    s = 1
  elif s == "formerly smoked":
    s = 2
  elif s == "smokes":
    s = 3

  pred = model.predict([[g,a,hyt,ht,m,w,r,gl,b,s]])
  return pred[0]


#INPUT - FROM - USER
g = input("Enter your gender : ")
g = g.lower()

a = int(input("Enter your age : "))

hyt = input("Do you have hypertension ? yes or no : ")
hyt = hyt.lower()

ht = input("Do you have any heart Disease ? yes or no : ")
ht = ht.lower()

m = input("Have you been Married ? yes or no : ")
m = m.lower()

w = input("Worktype ? private/self-employed/student/government/others : ")
w = w.lower()

r = input("residency type ? rural or urban ? : ")
r = r.lower()

gl = input('enter glucose levels. ? Enter value or type "i do not know" : ' )
gl = gl.lower()

b = int(input("Enter BMI"))

s = input("Smoking Status => unknown/never smoked/formerly smoked/smokes : ")
s = s.lower()


#call prediction function
op = prediction(g,a,hyt,ht,m,w,r,gl,b,s)
if op == 1:
  print("Person has chances of having Stroke")
else:
  print("Patient has no risk of Stroke")

Enter your genderfemale
Enter your age60
Do you have hypertension ? yes or nono
Do you have any heart Disease ? yes or nono
Have you been Married ? yes or nono
Worktype ? private/self-employed/student/government/othersothers
residency type ? rural or urban ?rural
enter glucose levels. ? Enter value or type "i do not know" 300
Enter BMI30
Smoking Status => unknown/never smoked/formerly smoked/smokesunknown
Patient has no risk of Stroke

In [38]:
#create a pkl model file

import pickle
pickle.dump(model,open('model.pkl','wb'))